# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CSS', 'CSS'), ('Info-security', 'Information Security'), ('JAVA', 'JAVA'), ('HTML5', 'HTML5'), ('Teamwork', 'Teamwork'), ('Networks', 'Networking'), ('Data security', 'Data security'), ('Programming', 'Programming'), ('C++', 'C++'), ('PHP', 'PHP')], max_length=128)),
                ('student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
