# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='additional',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, choices=[('CSS', 'CSS'), ('Info-security', 'Information Security'), ('JAVA', 'JAVA'), ('HTML5', 'HTML5'), ('Teamwork', 'Teamwork'), ('Networks', 'Networking'), ('Data security', 'Data security'), ('Programming', 'Programming'), ('C++', 'C++'), ('PHP', 'PHP')], max_length=128),
        ),
    ]
