# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 16:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0003_auto_20160421_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='additional',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Additional'),
        ),
    ]
