# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0006_auto_20160422_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
