# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0007_auto_20160422_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='id',
        ),
        migrations.AddField(
            model_name='skill',
            name='identifier',
            field=models.CharField(default=None, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
