# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-01 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0008_auto_20160426_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
