# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 20:13
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_ID', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Must be 9 unique numbers', regex='^[0-9]{9,9}$')])),
                ('first_name', models.CharField(max_length=128)),
                ('middle_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('year', models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd')], max_length=1)),
                ('degree', models.CharField(choices=[('IT', 'Information Technology'), ('CS', 'Computer Science')], max_length=2)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_pictures')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
