# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 15:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_ID',
            field=models.CharField(max_length=9, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Must be 9 unique numbers', regex='^[0-9]{9,9}$')]),
        ),
    ]
