# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 10:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20160314_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_ID',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='nomatch', message='Must be 9 unique numbers', regex='^[0-9]{9,9}$')]),
        ),
    ]
