# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20160314_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('CS', 'Computer Science')], max_length=2),
        ),
    ]
