# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_curricular', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_curricular',
            name='type_of_exp',
            field=models.CharField(choices=[('Work', 'Work Experience'), ('Society', 'Society Experience'), ('Volunteering', 'Volunteering Experience')], max_length=12, verbose_name='Type of experience'),
        ),
    ]
