# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_student_student_id'),
        ('extra_curricular', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra_curricular',
            name='student_ID',
        ),
        migrations.AddField(
            model_name='extra_curricular',
            name='user',
            field=models.OneToOneField(default='sc13jas', on_delete=django.db.models.deletion.CASCADE, to='student.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extra_curricular',
            name='type_of_exp',
            field=models.CharField(choices=[('WE', 'Work Experience'), ('SE', 'Society Experience'), ('VE', 'Volunteering Experience')], max_length=2),
        ),
    ]
