# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra_curricular', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra_curricular',
            name='slug',
        ),
    ]
