# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-01 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumni',
            fields=[
                ('identifier', models.CharField(default=None, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('course', models.CharField(choices=[('Information Technology', 'Information Technology'), ('Computer Science', 'Computer Science')], max_length=30)),
                ('faculty', models.CharField(choices=[('Art', 'Faculty of Art'), ('Bio', 'Faculty of Biological Sciences'), ('Bus', 'Faculty of Business'), ('Eds', 'Faculty of Education, Social Sciences and Law'), ('Eng', 'Faculty of Engineering'), ('Env', 'Faculty of Enviroment'), ('Mat', 'Faculty of Mathematics and Physical Sciences'), ('Med', 'Faculty of Medicine and Health'), ('Per', 'Faculty of Performance, Visual Arts and Communications')], max_length=60)),
                ('sector', models.CharField(choices=[('Accountancy, banking and finance', 'Accountancy, banking and finance'), ('Business, consulting and management', 'Business, consulting and management'), ('Charity and voluntary work', 'Charity and voluntary work'), ('Creative arts and design', 'Creative arts and design'), ('Energy and utilities', 'Energy and utilities'), ('Engineering and manufacturing', 'Engineering and manufacturing'), ('Environment and agriculture', 'Environment and agriculture'), ('Healthcare', 'Healthcare'), ('Hospitality and events management', 'Hospitality and events management'), ('IT', 'IT'), ('Law', 'Law'), ('Law enforcement and security', 'Law enforcement and security'), ('Leisure, sport and tourism', 'Leisure, sport and tourism'), ('Marketing, advertising and PR', 'Marketing, advertising and PR'), ('Media and internet', 'Media and internet'), ('Property and construction', 'Property and construction'), ('Public services and administration', 'Public services and administration'), ('Recruitment and HR', 'Recruitment and HR'), ('Sales and Retail', 'Sales and Retail'), ('Science and pharmaceuticals', 'Science and pharmaceuticals'), ('Social care', 'Social care'), ('Teaching and education', 'Teaching and education'), ('Transport and logistics', 'Transport and logistics')], max_length=60)),
                ('email_address', models.EmailField(max_length=254)),
                ('self_employed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
            ],
        ),
    ]
