# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_auto_20160421_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='sector',
            field=models.CharField(choices=[('Accountancy, banking and finance', 'Accountancy, banking and finance'), ('Business, consulting and management', 'Business, consulting and management'), ('Charity and voluntary work', 'Charity and voluntary work'), ('Creative arts and design', 'Creative arts and design'), ('Energy and utilities', 'Energy and utilities'), ('Engineering and manufacturing', 'Engineering and manufacturing'), ('Environment and agriculture', 'Environment and agriculture'), ('Healthcare', 'Healthcare'), ('Hospitality and events management', 'Hospitality and events management'), ('IT', 'IT'), ('Law', 'Law'), ('Law enforcement and security', 'Law enforcement and security'), ('Leisure, sport and tourism', 'Leisure, sport and tourism'), ('Marketing, advertising and PR', 'Marketing, advertising and PR'), ('Media and internet', 'Media and internet'), ('Property and construction', 'Property and construction'), ('Public services and administration', 'Public services and administration'), ('Recruitment and HR', 'Recruitment and HR'), ('Sales and Retail', 'Sales and Retail'), ('Science and pharmaceuticals', 'Science and pharmaceuticals'), ('Social care', 'Social care'), ('Teaching and education', 'Teaching and education'), ('Transport and logistics', 'Transport and logistics')], max_length=60),
        ),
    ]
